# Generated by Django 6.1 on 2026-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='Title',
            new_name='Github',
        ),
        migrations.RemoveField(
            model_name='social',
            name='Link',
        ),
        migrations.AddField(
            model_name='social',
            name='Instagram',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='Telegram',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
