# Generated by Django 6.1 on 2026-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_title_social_github_remove_social_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='Github',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='social',
            name='Instagram',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='social',
            name='Telegram',
            field=models.URLField(max_length=50),
        ),
    ]
